[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Root=[IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
. (Join-Path $Root 'scripts\Universaarl-Control.Common.ps1')
$Temp=Join-Path ([IO.Path]::GetTempPath()) "uabc-contract-$([Guid]::NewGuid().ToString('N'))"
$script:Passed=0
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw "TEST FEHLGESCHLAGEN: $Message"};$script:Passed++}
function Assert-Throws([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action|Out-Null}catch{$ok=$true};Assert-True $ok $Message}
function InvokeFixtureGit([string]$Repo,[string[]]$GitArgs){$env:GIT_OPTIONAL_LOCKS='0';$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';$out=@(& git.exe -c core.autocrlf=false -C $Repo @GitArgs 2>&1);if($LASTEXITCODE-ne 0){throw ($out-join"`n")};($out-join"`n").Trim()}finally{$ErrorActionPreference=$old}}
function WriteUtf8([string]$Path,[string]$Text){$dir=Split-Path -Parent $Path;if($dir){[IO.Directory]::CreateDirectory($dir)|Out-Null};[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Sha([byte[]]$Bytes){Get-UniversaarlBytesSha256 $Bytes}
try{
 [IO.Directory]::CreateDirectory($Temp)|Out-Null
 $spectra=Join-Path $Temp 'spectra';[IO.Directory]::CreateDirectory($spectra)|Out-Null;InvokeFixtureGit $spectra @('init','--quiet')|Out-Null;InvokeFixtureGit $spectra @('config','user.name','Fixture')|Out-Null;InvokeFixtureGit $spectra @('config','user.email','fixture@example.invalid')|Out-Null
 WriteUtf8 (Join-Path $spectra 'payload.txt') "alpha`n";InvokeFixtureGit $spectra @('add','payload.txt')|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','source')|Out-Null;$source=InvokeFixtureGit $spectra @('rev-parse','HEAD')
 $bytes=[Text.UTF8Encoding]::new($false).GetBytes("alpha`n");$fileSha=Sha $bytes;$legacyBundle=Sha ([Text.UTF8Encoding]::new($false).GetBytes("$fileSha  payload.txt`n"));$bundle=Sha ([Text.UTF8Encoding]::new($false).GetBytes("$fileSha  100644  payload.txt`n"))
 $sourceTree=InvokeFixtureGit $spectra @('rev-parse', 'HEAD^{tree}')
 $manifest=[ordered]@{schema_version=4;product_id='spectra';release_version='1.2.3-alpha.1';release_kind='installable_blueprint';manifest_state='final';release_date='2026-07-11';expected_tag='spectra-v1.2.3-alpha.1';source_commit=$source;source_tree=$sourceTree;consumer_mode='INSTALLABLE_BLUEPRINT';installable_blueprint=$true;blueprint_version='1.2.3-alpha.1';payload=[ordered]@{digest_algorithm='SHA-256';bundle_digest=$bundle;file_count=1;checksums_file='checksums.sha256';files=@([ordered]@{path='payload.txt';sha256=$fileSha;size_bytes=$bytes.Length;mode='100644'})};binding_requirements=@('annotated immutable release tag');excluded_from_payload=@('release/versions');known_limits=@('synthetic fixture')}
 $manifestPath='release/versions/1.2.3-alpha.1/release-manifest.json';$checksumsPath='release/versions/1.2.3-alpha.1/checksums.sha256'
 $candidate=($manifest|ConvertTo-Json -Depth 8|ConvertFrom-Json);$candidate.schema_version=1;$candidate.PSObject.Properties.Remove('source_tree');$candidate.manifest_state='candidate';$candidate.source_commit=$null;$candidate.payload.bundle_digest=$legacyBundle;$candidate.payload.files[0].PSObject.Properties.Remove('mode')
 WriteUtf8 (Join-Path $spectra $manifestPath) (($candidate|ConvertTo-Json -Depth 8)+"`n");WriteUtf8 (Join-Path $spectra $checksumsPath) "$fileSha  payload.txt`n";InvokeFixtureGit $spectra @('add','.')|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','candidate')|Out-Null;$candidateCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD')
 $candidateProof=Test-UniversaarlSpectraCandidate $spectra $candidateCommit '1.2.3-alpha.1';Assert-True $candidateProof.fullValidationPassed 'Positiver Spectra-Candidate wurde abgelehnt.'
 $badCandidate=($candidate|ConvertTo-Json -Depth 8|ConvertFrom-Json);$badCandidate.payload.bundle_digest=('0'*64);WriteUtf8 (Join-Path $spectra $manifestPath) (($badCandidate|ConvertTo-Json -Depth 8)+"`n");InvokeFixtureGit $spectra @('add',$manifestPath)|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','bad candidate')|Out-Null;$badCandidateCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSpectraCandidate $spectra $badCandidateCommit '1.2.3-alpha.1'} 'Falscher Candidate-Bundledigest wurde akzeptiert.'
 WriteUtf8 (Join-Path $spectra $manifestPath) (($manifest|ConvertTo-Json -Depth 8)+"`n");InvokeFixtureGit $spectra @('add',$manifestPath)|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','manifest')|Out-Null;$tagCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD');InvokeFixtureGit $spectra @('tag','-a','spectra-v1.2.3-alpha.1','-m','fixture')|Out-Null
 $binding=[pscustomobject]@{bindingStatus='BOUND';productId='spectra';technicalRepositoryName='BCProjectOS';repositoryUrl='https://github.com/sivla/BCProjectOS.git';releaseVersion='1.2.3-alpha.1';releaseTag='spectra-v1.2.3-alpha.1';tagCommit=$tagCommit;manifestPath=$manifestPath;manifestSourceCommit=$source;consumerMode='INSTALLABLE_BLUEPRINT';installableBlueprint=$true;digestAlgorithm='SHA-256';payloadBundleDigest=$bundle}
 $proof=Test-UniversaarlSpectraReleaseBinding $spectra $binding;Assert-True $proof.fullValidationPassed 'Positive Spectra-Bindung wurde abgelehnt.'
 $bad=$binding.PSObject.Copy();$bad.payloadBundleDigest=('0'*64);Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Falscher Produktdigest wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.tagCommit=('0'*40);Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Falscher Tag-Commit wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.releaseVersion='1.2.4';$bad.releaseTag='spectra-v1.2.4';Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Fehlender Release-Tag wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.releaseVersion='1.2.4';Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Manifest-/Versionskonflikt wurde akzeptiert.'
 InvokeFixtureGit $spectra @('tag','spectra-v9.9.9')|Out-Null;Assert-Throws {Resolve-UniversaarlAnnotatedTag $spectra 'spectra-v9.9.9'} 'Leichtgewichtiger Tag wurde akzeptiert.'
 foreach($unsafe in @('../x','a\b','C:/x','https:x','a//b','./x')){Assert-Throws {Assert-UniversaarlContractPath $unsafe} "Unsicherer Pfad '$unsafe' wurde akzeptiert."}

 $blue=Join-Path $Temp 'blueprint';[IO.Directory]::CreateDirectory($blue)|Out-Null;InvokeFixtureGit $blue @('init','--quiet')|Out-Null;InvokeFixtureGit $blue @('config','user.name','Fixture')|Out-Null;InvokeFixtureGit $blue @('config','user.email','fixture@example.invalid')|Out-Null
 $indexPath='exports/project-data/v1/index.yaml';$phase2='evidence/simulation/phase-2-p2p-o2c.yaml';$phase3='evidence/simulation/phase-3-cash-inventory-close.yaml';$payloadPath='project/bc-basic/project-plan.yaml'
 $indexHeader="schemaVersion: 1`ncontractId: UABC-PROJECT-DATA-V1`nprojectId: UABC-BC-BASIC-001`nrouteKey: bc-basic`nreadOnly: true`ncontractRole: repository-relative-data-allowlist`npathSemantics: repository-relative`nallowedBranch: codex/universaarl-projekt`nvalidationStatus: branch-commit-validierung-erforderlich`nartifacts:`n"
 $goodArtifacts="  - { id: UABC-FIXTURE-PLAN-001, kindId: project-plan, path: $payloadPath, format: yaml, required: true }`n  - { id: UABC-FIXTURE-PHASE2-001, kindId: simulation, path: $phase2, format: yaml, required: true }`n  - { id: UABC-FIXTURE-PHASE3-001, kindId: simulation, path: $phase3, format: yaml, required: true }`n"
 WriteUtf8 (Join-Path $blue $indexPath) ($indexHeader+$goodArtifacts);WriteUtf8 (Join-Path $blue $payloadPath) "status: simulated`n";WriteUtf8 (Join-Path $blue $phase2) "status: synthetic-complete`n";WriteUtf8 (Join-Path $blue $phase3) "status: synthetic-complete`n";WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') "{ `"legacy`": true, `"producerCommitSha`": `"stale`" }`n";InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','branch index')|Out-Null;$branchCommit=InvokeFixtureGit $blue @('rev-parse','HEAD')
 $branchProof=Test-UniversaarlBranchIndex $blue $branchCommit 'codex/universaarl-projekt';Assert-True $branchProof.fullValidationPassed 'Positiver Branch-Index-Vertrag wurde abgelehnt.';Assert-True ($branchProof.legacySnapshotRequired -eq $false) 'Legacy-Manifest wurde im Branch-Modus erzwungen.'
 Assert-Throws {Test-UniversaarlBranchIndex $blue $branchCommit 'main'} 'Falscher Branch wurde akzeptiert.'
 WriteUtf8 (Join-Path $blue $indexPath) ($indexHeader+$goodArtifacts.Replace('project/bc-basic/project-plan.yaml','../unsafe.yaml'));InvokeFixtureGit $blue @('add',$indexPath)|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','unsafe path')|Out-Null;$badCommit=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlBranchIndex $blue $badCommit 'codex/universaarl-projekt'} 'Unsicherer Indexpfad wurde akzeptiert.'
 WriteUtf8 (Join-Path $blue $indexPath) ($indexHeader+"  - { id: UABC-FIXTURE-PLAN-001, kindId: project-plan, path: $payloadPath, format: yaml, required: true }`n  - { id: UABC-FIXTURE-PLAN-001, kindId: simulation, path: $phase2, format: yaml, required: true }`n  - { id: UABC-FIXTURE-PHASE3-001, kindId: simulation, path: $phase3, format: yaml, required: true }`n");InvokeFixtureGit $blue @('add',$indexPath)|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','duplicate id')|Out-Null;$badCommit=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlBranchIndex $blue $badCommit 'codex/universaarl-projekt'} 'Doppelte Index-ID wurde akzeptiert.'
 WriteUtf8 (Join-Path $blue $indexPath) ($indexHeader+"  - { id: UABC-FIXTURE-PLAN-001, kindId: project-plan, path: $payloadPath, format: yaml, required: true }`n  - { id: UABC-FIXTURE-PHASE3-001, kindId: simulation, path: $phase3, format: yaml, required: true }`n");InvokeFixtureGit $blue @('add',$indexPath)|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','missing phase')|Out-Null;$badCommit=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlBranchIndex $blue $badCommit 'codex/universaarl-projekt'} 'Fehlende aktuelle Simulationsevidence wurde akzeptiert.'

 $portableIndex="schemaVersion: 1`ncontractId: UABC-PROJECT-DATA-V1`nprojectId: UABC-BC-BASIC-001`nrouteKey: bc-basic`nartifacts:`n  - id: UABC-FIXTURE-PLAN-001`n    kindId: project-plan`n    path: $payloadPath`n    format: yaml`n    required: true`n"
 WriteUtf8 (Join-Path $blue $indexPath) $portableIndex;WriteUtf8 (Join-Path $blue $payloadPath) "status: portable`n";InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','portable source')|Out-Null;$portableSource=InvokeFixtureGit $blue @('rev-parse','HEAD')
 $releaseId='UABC-PORTABLE-PILOT-0003';$releaseRoot="exports/project-data/v1/snapshots/releases/$releaseId";$releaseDir=Join-Path $blue ($releaseRoot-replace'/','\');$releaseData=Join-Path $releaseDir 'data'
 $payloadObject=[ordered]@{schemaVersion=1;contractId='UABC-PORTABLE-SNAPSHOT-PILOT-V1';releaseId=$releaseId;customerId='UABC-CUSTOMER-001';projectId='UABC-BC-BASIC-001';classification='synthetic-local-simulation';sourceInventory=[ordered]@{checkpoint=[ordered]@{checkpointId='FIXTURE';capturedAt='2026-07-14T00:00:00Z';mode='local-simulation';producerCommitProvenance=$portableSource;externalReadPerformed=$false};pages=@()};deltas=@();views=[ordered]@{customer=[ordered]@{approvedKnowledgeChanges=@();coverage=@()};internal=[ordered]@{knowledgeChanges=@();contradictions=@();brownfieldReconciliation=[ordered]@{baseline='Fixture';rows=@()}}};visibilityBoundary=[ordered]@{allowed=@('customer','internal');customerSelector='views.customer';internalSelector='views.internal';foreignCustomerDataAllowed=$false};truthBoundary=[ordered]@{liveExecutionClaimed=$false;externalSyncClaimed=$false;uncheckedKnowledgePromoted=$false}}
 $knowledgePath="$releaseRoot/payload.json";WriteUtf8 (Join-Path $blue ($knowledgePath-replace'/','\')) (($payloadObject|ConvertTo-Json -Depth 12)+"`n");$knowledgeBytes=[IO.File]::ReadAllBytes((Join-Path $blue ($knowledgePath-replace'/','\')));$knowledgeSha=Sha $knowledgeBytes
 $fragmentPath="$releaseRoot/catalog-fragment.json";$fragmentObject=[ordered]@{schemaVersion=1;fragmentContract='uabc-customer-project-fragment-v1';customerId='UABC-CUSTOMER-001';fixtureOnly=$false;projects=@([ordered]@{projectId='UABC-BC-BASIC-001';routeKey='bc-basic';visibility='customer';snapshotReleaseId=$releaseId;consumerEligible=$true;publishEligible=$true});payload=[ordered]@{path=$knowledgePath;sha256=$knowledgeSha;sizeBytes=$knowledgeBytes.Length};projectData=[ordered]@{contractId='UABC-PROJECT-DATA-V1';sourceCommit=$portableSource;artifactCount=1}}
 WriteUtf8 (Join-Path $blue ($fragmentPath-replace'/','\')) (($fragmentObject|ConvertTo-Json -Depth 12)+"`n");$fragmentBytes=[IO.File]::ReadAllBytes((Join-Path $blue ($fragmentPath-replace'/','\')));$fragmentSha=Sha $fragmentBytes
 $indexReleasePath="$releaseRoot/data/$indexPath";$sourceReleasePath="$releaseRoot/data/$payloadPath";[IO.Directory]::CreateDirectory((Split-Path -Parent (Join-Path $blue ($indexReleasePath-replace'/','\'))))|Out-Null;[IO.File]::WriteAllBytes((Join-Path $blue ($indexReleasePath-replace'/','\')),[IO.File]::ReadAllBytes((Join-Path $blue ($indexPath-replace'/','\'))));[IO.Directory]::CreateDirectory((Split-Path -Parent (Join-Path $blue ($sourceReleasePath-replace'/','\'))))|Out-Null;[IO.File]::WriteAllBytes((Join-Path $blue ($sourceReleasePath-replace'/','\')),[IO.File]::ReadAllBytes((Join-Path $blue ($payloadPath-replace'/','\'))))
 $indexBytes=[IO.File]::ReadAllBytes((Join-Path $blue ($indexReleasePath-replace'/','\')));$sourceBytes=[IO.File]::ReadAllBytes((Join-Path $blue ($sourceReleasePath-replace'/','\')))
 function NewPortableRecord([string]$Kind,[string]$Id,$SourcePath,[string]$Format,[string]$Path,[byte[]]$Bytes){$digest=Sha $Bytes;[ordered]@{kind=$Kind;id=$Id;sourcePath=$SourcePath;format=$Format;selector=$null;path=$Path;sizeBytes=$Bytes.Length;sha256=$digest;transports=@([ordered]@{type='filesystem';relativePath=$Path;sha256=$digest},[ordered]@{type='https';relativePath=$Path;sha256=$digest})}}
 $records=@((NewPortableRecord 'knowledge-payload' 'UABC-SNAPSHOT-KNOWLEDGE-0003' $null 'json' $knowledgePath $knowledgeBytes),(NewPortableRecord 'catalog-fragment' 'UABC-SNAPSHOT-FRAGMENT-0003' $null 'json' $fragmentPath $fragmentBytes),(NewPortableRecord 'project-index' 'UABC-SNAPSHOT-INDEX-0003' $indexPath 'yaml' $indexReleasePath $indexBytes),(NewPortableRecord 'project-source' 'UABC-FIXTURE-PLAN-001' $payloadPath 'yaml' $sourceReleasePath $sourceBytes))
 $tagObject=InvokeFixtureGit $spectra @('rev-parse','refs/tags/spectra-v1.2.3-alpha.1')
 $portableManifest=[ordered]@{schemaVersion=1;manifestContract='uabc-portable-snapshot-release-v1';releaseId=$releaseId;immutable=$true;producer=[ordered]@{customerId='UABC-CUSTOMER-001';projectIds=@('UABC-BC-BASIC-001');commitShaProvenance=$portableSource};releaseBinding=[ordered]@{bindingStatus='BOUND_BCPROJECTOS_RELEASE';pendingReason=$null;consumerEligible=$true;publishEligible=$true;requiredEvidence=@('annotatedTag','peeledCommit','finalManifest','productDigest','platformMatrix');spectraReleaseBinding=[ordered]@{evidencePath='evidence/spectra.yaml';productId='spectra';technicalRepositoryName='BCProjectOS';repositoryUrl='https://github.com/sivla/BCProjectOS.git';releaseVersion='1.2.3-alpha.1';releaseTag='spectra-v1.2.3-alpha.1';annotatedTagObject=$tagObject;peeledCommit=$tagCommit;manifestPath=$manifestPath;manifestSourceCommit=$source;sourceTree=$sourceTree;consumerMode='INSTALLABLE_BLUEPRINT';installableBlueprint=$true;digestAlgorithm='SHA-256';payloadBundleDigest=$bundle;platformEvidenceStatus='passed';platformEvidenceRun='https://github.com/sivla/BCProjectOS/actions/runs/1'}};pathSemantics='repository-relative';byteContract='identical-canonical-bytes';sourceInventoryDigest=('a'*64);projectData=[ordered]@{contractId='UABC-PROJECT-DATA-V1';indexSourcePath=$indexPath;indexPath=$indexReleasePath;sourceCommit=$portableSource;artifactCount=1};files=$records;validationStatus='validated-release'}
 $portableManifestPath="$releaseRoot/manifest.json";WriteUtf8 (Join-Path $blue ($portableManifestPath-replace'/','\')) (($portableManifest|ConvertTo-Json -Depth 16)+"`n");$portableManifestBytes=[IO.File]::ReadAllBytes((Join-Path $blue ($portableManifestPath-replace'/','\')));$portableManifestSha=Sha $portableManifestBytes
 $current=[ordered]@{schemaVersion=1;pointerContract='uabc-portable-snapshot-current-v1';customerId='UABC-CUSTOMER-001';projectId='UABC-BC-BASIC-001';currentReleaseId=$releaseId;manifestPath=$portableManifestPath;manifestSha256=$portableManifestSha;bindingStatus='BOUND_BCPROJECTOS_RELEASE';consumerEligible=$true;publishEligible=$true;updatedAt='2026-07-14T00:00:00Z'}
 WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshots/current.json') (($current|ConvertTo-Json -Depth 8)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','portable release')|Out-Null;$portableCommit=InvokeFixtureGit $blue @('rev-parse','HEAD')
 $portableProof=Test-UniversaarlPortableSnapshotRelease $blue $portableCommit $spectra;Assert-True ($portableProof.fullValidationPassed -and $portableProof.fileCount -eq 4) 'Positiver portabler Snapshotrelease wurde abgelehnt.'
 WriteUtf8 (Join-Path $blue ($sourceReleasePath-replace'/','\')) "status: manipuliert`n";InvokeFixtureGit $blue @('add',$sourceReleasePath)|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','tampered portable release')|Out-Null;$tamperedPortableCommit=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlPortableSnapshotRelease $blue $tamperedPortableCommit $spectra} 'Manipulierte portable Releasebytes wurden akzeptiert.'
 Write-Host "Vertragsvalidator-Fixtures bestanden: $script:Passed"
}finally{if(Test-Path $Temp){Remove-Item -LiteralPath $Temp -Recurse -Force}}
