[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Root=[IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
. (Join-Path $Root 'scripts\Universaarl-Control.Common.ps1')
$Temp=Join-Path ([IO.Path]::GetTempPath()) "uabc-contract-$([Guid]::NewGuid().ToString('N'))"
$script:Passed=0
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw "TEST FEHLGESCHLAGEN: $Message"};$script:Passed++}
function Assert-Throws([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action|Out-Null}catch{$ok=$true};Assert-True $ok $Message}
function InvokeFixtureGit([string]$Repo,[string[]]$GitArgs){$env:GIT_OPTIONAL_LOCKS='0';$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';$out=@(& git.exe -c core.autocrlf=false -C $Repo @GitArgs 2>&1);if($LASTEXITCODE-ne 0){throw ($out-join"`n")};($out-join"`n").Trim()}finally{$ErrorActionPreference=$old}}
function WriteUtf8([string]$Path,[string]$Text){$dir=Split-Path -Parent $Path;if($dir){[IO.Directory]::CreateDirectory($dir)|Out-Null};[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Sha([byte[]]$Bytes){Get-UniversaarlBytesSha256 $Bytes}
try{
 [IO.Directory]::CreateDirectory($Temp)|Out-Null
 $spectra=Join-Path $Temp 'spectra';[IO.Directory]::CreateDirectory($spectra)|Out-Null;InvokeFixtureGit $spectra @('init','--quiet')|Out-Null;InvokeFixtureGit $spectra @('config','user.name','Fixture')|Out-Null;InvokeFixtureGit $spectra @('config','user.email','fixture@example.invalid')|Out-Null
 WriteUtf8 (Join-Path $spectra 'payload.txt') "alpha`n";InvokeFixtureGit $spectra @('add','payload.txt')|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','source')|Out-Null;$source=InvokeFixtureGit $spectra @('rev-parse','HEAD')
 $bytes=[Text.UTF8Encoding]::new($false).GetBytes("alpha`n");$fileSha=Sha $bytes;$bundle=Sha ([Text.UTF8Encoding]::new($false).GetBytes("$fileSha  payload.txt`n"))
 $manifest=[ordered]@{schema_version=1;product_id='spectra';release_version='1.2.3-alpha.1';release_kind='installable_blueprint';manifest_state='final';release_date='2026-07-11';expected_tag='spectra-v1.2.3-alpha.1';source_commit=$source;consumer_mode='INSTALLABLE_BLUEPRINT';installable_blueprint=$true;blueprint_version='1.2.3-alpha.1';payload=[ordered]@{digest_algorithm='SHA-256';bundle_digest=$bundle;file_count=1;checksums_file='checksums.sha256';files=@([ordered]@{path='payload.txt';sha256=$fileSha;size_bytes=$bytes.Length})};binding_requirements=@('annotated immutable release tag');excluded_from_payload=@('release/versions');known_limits=@('synthetic fixture')}
 $manifestPath='release/versions/1.2.3-alpha.1/release-manifest.json';$checksumsPath='release/versions/1.2.3-alpha.1/checksums.sha256'
 $candidate=($manifest|ConvertTo-Json -Depth 8|ConvertFrom-Json);$candidate.manifest_state='candidate';$candidate.source_commit=$null
 WriteUtf8 (Join-Path $spectra $manifestPath) (($candidate|ConvertTo-Json -Depth 8)+"`n");WriteUtf8 (Join-Path $spectra $checksumsPath) "$fileSha  payload.txt`n";InvokeFixtureGit $spectra @('add','.')|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','candidate')|Out-Null;$candidateCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD')
 $candidateProof=Test-UniversaarlSpectraCandidate $spectra $candidateCommit '1.2.3-alpha.1';Assert-True $candidateProof.fullValidationPassed 'Positiver Spectra-Candidate wurde abgelehnt.'
 $badCandidate=($candidate|ConvertTo-Json -Depth 8|ConvertFrom-Json);$badCandidate.payload.bundle_digest=('0'*64);WriteUtf8 (Join-Path $spectra $manifestPath) (($badCandidate|ConvertTo-Json -Depth 8)+"`n");InvokeFixtureGit $spectra @('add',$manifestPath)|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','bad candidate')|Out-Null;$badCandidateCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSpectraCandidate $spectra $badCandidateCommit '1.2.3-alpha.1'} 'Falscher Candidate-Bundledigest wurde akzeptiert.'
 WriteUtf8 (Join-Path $spectra $manifestPath) (($manifest|ConvertTo-Json -Depth 8)+"`n");InvokeFixtureGit $spectra @('add',$manifestPath)|Out-Null;InvokeFixtureGit $spectra @('commit','--quiet','-m','manifest')|Out-Null;$tagCommit=InvokeFixtureGit $spectra @('rev-parse','HEAD');InvokeFixtureGit $spectra @('tag','-a','spectra-v1.2.3-alpha.1','-m','fixture')|Out-Null
 $binding=[pscustomobject]@{bindingStatus='BOUND';productId='spectra';technicalRepositoryName='BCProjectOS';repositoryUrl='https://github.com/sivla/BCProjectOS.git';releaseVersion='1.2.3-alpha.1';releaseTag='spectra-v1.2.3-alpha.1';tagCommit=$tagCommit;manifestPath=$manifestPath;manifestSourceCommit=$source;consumerMode='INSTALLABLE_BLUEPRINT';installableBlueprint=$true;digestAlgorithm='SHA-256';payloadBundleDigest=$bundle}
 $proof=Test-UniversaarlSpectraReleaseBinding $spectra $binding;Assert-True $proof.fullValidationPassed 'Positive Spectra-Bindung wurde abgelehnt.'
 $bad=$binding.PSObject.Copy();$bad.payloadBundleDigest=('0'*64);Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Falscher Produktdigest wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.tagCommit=('0'*40);Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Falscher Tag-Commit wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.releaseVersion='1.2.4';$bad.releaseTag='spectra-v1.2.4';Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Fehlender Release-Tag wurde akzeptiert.'
 $bad=$binding.PSObject.Copy();$bad.releaseVersion='1.2.4';Assert-Throws {Test-UniversaarlSpectraReleaseBinding $spectra $bad} 'Manifest-/Versionskonflikt wurde akzeptiert.'
 InvokeFixtureGit $spectra @('tag','spectra-v9.9.9')|Out-Null;Assert-Throws {Resolve-UniversaarlAnnotatedTag $spectra 'spectra-v9.9.9'} 'Leichtgewichtiger Tag wurde akzeptiert.'
 foreach($unsafe in @('../x','a\b','C:/x','https:x','a//b','./x')){Assert-Throws {Assert-UniversaarlContractPath $unsafe} "Unsicherer Pfad '$unsafe' wurde akzeptiert."}

 $blue=Join-Path $Temp 'blueprint';[IO.Directory]::CreateDirectory($blue)|Out-Null;InvokeFixtureGit $blue @('init','--quiet')|Out-Null;InvokeFixtureGit $blue @('config','user.name','Fixture')|Out-Null;InvokeFixtureGit $blue @('config','user.email','fixture@example.invalid')|Out-Null
 $indexPath='exports/project-data/v1/index.yaml';$payloadPath='exports/project-data/v1/data.json';$schemaPath='governance/schemas/project-snapshot-manifest.schema.json';$bindingPath='governance/consumer-bindings.yaml'
 $required=@('schemaVersion','producerId','projectId','contractId','producerCommitSha','schemaPath','indexPath','consumer','spectraReleaseBinding','consumerBindingDigest','payloadDigestFormat','index','payloads','payloadBundleDigest','validationStatus');$fixtureSchema=[ordered]@{'$schema'='https://json-schema.org/draft/2020-12/schema';'$id'='urn:universaarl:schema:project-snapshot-manifest:v1';type='object';additionalProperties=$false;required=$required;properties=[ordered]@{}}
 WriteUtf8 (Join-Path $blue $indexPath) "schemaVersion: 1`nartifacts:`n  - { id: UABC-FIXTURE-001, kindId: fixture, path: exports/project-data/v1/data.json, format: json, required: true }`n";WriteUtf8 (Join-Path $blue $payloadPath) "{}`n";WriteUtf8 (Join-Path $blue $schemaPath) (($fixtureSchema|ConvertTo-Json -Depth 5)+"`n");WriteUtf8 (Join-Path $blue $bindingPath) "spectraReleaseBinding:`n  bindingStatus: BOUND`n";InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','A')|Out-Null;$A=InvokeFixtureGit $blue @('rev-parse','HEAD')
 function Record([string]$Path){$e=Get-UniversaarlBlobEntry $blue $A $Path -Required;$b=Get-UniversaarlGitBlobBytes $blue $e.object;[ordered]@{path=$Path;gitMode='100644';sizeBytes=$b.Length;sha256=(Sha $b)}}
 $idx=Record $indexPath;$pay=Record $payloadPath;$bindEntry=Get-UniversaarlBlobEntry $blue $A $bindingPath -Required;$bindDigest=Sha (Get-UniversaarlGitBlobBytes $blue $bindEntry.object)
 $recordBytes=@();foreach($r in @($pay,$idx)){ $recordBytes += [Text.UTF8Encoding]::new($false).GetBytes("$($r.path)`0100644`0$($r.sizeBytes)`0$($r.sha256)`n") };$snapshotDigest=Sha ([byte[]]$recordBytes)
 $snap=[ordered]@{schemaVersion=1;producerId='blueprint';projectId='UABC-BC-BASIC-001';contractId='UABC-PROJECT-DATA-V1';producerCommitSha=$A;schemaPath=$schemaPath;indexPath=$indexPath;consumer=[ordered]@{consumerId='project-twin';repositoryUrl='https://github.com/sivla/FiBu.git';branch='codex/universaarl-projekt-twin';access='nur-lesend'};spectraReleaseBinding=[ordered]@{bindingStatus='BOUND';productId='spectra';technicalRepositoryName='BCProjectOS';repositoryUrl='https://github.com/sivla/BCProjectOS.git';releaseVersion=$binding.releaseVersion;releaseTag=$binding.releaseTag;tagCommit=$binding.tagCommit;manifestPath=$binding.manifestPath;manifestSourceCommit=$binding.manifestSourceCommit;consumerMode=$binding.consumerMode;installableBlueprint=$true;digestAlgorithm='SHA-256';payloadBundleDigest=$bundle};consumerBindingDigest="sha256:$bindDigest";payloadDigestFormat='uabc-snapshot-records-v1';index=$idx;payloads=@([ordered]@{id='UABC-FIXTURE-001';path=$pay.path;selector=$null;gitMode=$pay.gitMode;sizeBytes=$pay.sizeBytes;sha256=$pay.sha256});payloadBundleDigest="sha256:$snapshotDigest";validationStatus='validated'}
 WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') (($snap|ConvertTo-Json -Depth 10)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','B')|Out-Null;$B=InvokeFixtureGit $blue @('rev-parse','HEAD')
 $snapshotProof=Test-UniversaarlSnapshotManifest $blue $B $binding;Assert-True $snapshotProof.fullValidationPassed 'Positiver Snapshot-A/B-Vertrag wurde abgelehnt.'
 $badSnap=($snap|ConvertTo-Json -Depth 10|ConvertFrom-Json);$badSnap.producerCommitSha=('0'*40);InvokeFixtureGit $blue @('reset','--hard',$A)|Out-Null;WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') (($badSnap|ConvertTo-Json -Depth 10)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','wrong producer')|Out-Null;$badB=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSnapshotManifest $blue $badB $binding} 'Falscher Produzentencommit wurde akzeptiert.'
 $badSnap=($snap|ConvertTo-Json -Depth 10|ConvertFrom-Json);$badSnap.payloadBundleDigest="sha256:$bundle";InvokeFixtureGit $blue @('reset','--hard',$A)|Out-Null;WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') (($badSnap|ConvertTo-Json -Depth 10)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','digest confusion')|Out-Null;$badB=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSnapshotManifest $blue $badB $binding} 'Produkt-/Snapshotdigest-Verwechslung wurde akzeptiert.'
 InvokeFixtureGit $blue @('reset','--hard',$A)|Out-Null;WriteUtf8 (Join-Path $blue 'extra.txt') "extra`n";WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') (($snap|ConvertTo-Json -Depth 10)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','extra path')|Out-Null;$badB=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSnapshotManifest $blue $badB $binding} 'Zusaetzlicher A/B-Pfad wurde akzeptiert.'
 InvokeFixtureGit $blue @('reset','--hard',$A)|Out-Null;InvokeFixtureGit $blue @('checkout','-b','fixture-side')|Out-Null;InvokeFixtureGit $blue @('commit','--allow-empty','--quiet','-m','side')|Out-Null;$side=InvokeFixtureGit $blue @('rev-parse','HEAD');InvokeFixtureGit $blue @('checkout','-B','fixture-main',$A)|Out-Null;WriteUtf8 (Join-Path $blue 'exports/project-data/v1/snapshot-manifest.json') (($snap|ConvertTo-Json -Depth 10)+"`n");InvokeFixtureGit $blue @('add','.')|Out-Null;InvokeFixtureGit $blue @('commit','--quiet','-m','manifest for merge')|Out-Null;InvokeFixtureGit $blue @('merge','--no-ff','--quiet','-m','merge fixture',$side)|Out-Null;$mergeB=InvokeFixtureGit $blue @('rev-parse','HEAD');Assert-Throws {Test-UniversaarlSnapshotManifest $blue $mergeB $binding} 'Snapshot-Mergecommit wurde akzeptiert.'
 Write-Host "Vertragsvalidator-Fixtures bestanden: $script:Passed"
}finally{if(Test-Path $Temp){Remove-Item -LiteralPath $Temp -Recurse -Force}}
